version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: provisioning-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: provisioning_db
    ports:
      - "5445:5432"

volumes:
  postgres_data:
